version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "pip"
    directory: "/content_services/onboarding_event_handler"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "pip"
    directory: "/content_services/onboarding"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "pip"
    directory: "/driver_db"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "pip"
    directory: "/content_services/inspector"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
