services:
  db:
    image: pgvector/pgvector:pg16
    restart: no
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  # webapp:
  #   build:
  #     context: ../webapp-frontend
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

  backend:
    image: 'backend:latest'
    restart: no
    ports:
      - "8888:8888"
    volumes:
      - ./backend/:/app
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    networks:
      - default
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
      - ENVIRONMENT=${ENVIRONMENT}
      - PYTHONPATH=/app
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - SECRET_KEY=${SECRET_KEY?Variable not set}
      - USERS_OPEN_REGISTRATION=${USERS_OPEN_REGISTRATION}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - SENTRY_DSN=${SENTRY_DSN}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_MGMT_API_CLIENT_ID=${AUTH0_MGMT_API_CLIENT_ID}
      - AUTH0_MGMT_API_CLIENT_SECRET=${AUTH0_MGMT_API_CLIENT_SECRET}
      - AUTH0_MGMT_API_AUDIENCE=${AUTH0_MGMT_API_AUDIENCE}
      - AWS_REGION=${AWS_REGION?Variable not set}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME?Variable not set}
      - PORT=8888
      - MODAL_TOKEN_ID=${MODAL_TOKEN_ID?Variable not set}
      - MODAL_TOKEN_SECRET=${MODAL_TOKEN_SECRET?Variable not set}
      - MODAL_ENVIRONMENT=${MODAL_ENVIRONMENT?dev}
  s3:
    image: localstack/localstack:s3-latest
    ports:
      - "127.0.0.1:4566:4566"
    networks:
      - default
    volumes:
      - "./scripts/init-s3-localstack.py:/etc/localstack/init/ready.d/init-s3.py"
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG:-0}
volumes:
  app-db-data:
