[project]
name = "python-backend-cdk"
version = "0.1.0"
description = ""
requires-python = ">=3.12,<3.13"
dependencies = [
    "aws-cdk-lib==2.227.0",
    "constructs>=10.0.0",
    "cdk-nag>2.0.0",
    "cdk-monitoring-constructs",
    "pydantic>2.0",
    "aws-cdk-aws-lambda-python-alpha==2.227.0a0",
    "toml>=0.10.2",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.3",
    "pytest-cov>=4.1.0",
    "mypy>=1.8.0",
    "pre-commit>=3.6.2",
    "pytest-mock>=3.12.0",
    "hypothesis>=6.142.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = false

[tool.uv.workspace]
members = [
    "backend",
    "content_services",
    "packages/*",
    "lambdas/*",
]
exclude = [
    "driver_data",
    "dev_stack",
]

[tool.poetry]
name = "python-backend-cdk"
version = "0.1.0"
description = ""
authors = ["Admin <admin@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
aws-cdk-lib = "2.227.0"
constructs = ">=10.0.0"
cdk-nag = ">2.0.0"
cdk-monitoring-constructs = "*"
pydantic = ">2.0"
aws-cdk-aws-lambda-python-alpha = "2.227.0a0"
toml = ">=0.10.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
mypy = "^1.8.0"
pre-commit = "^3.6.2"
pytest-mock = "^3.12.0"
hypothesis = "^6.142.4"

[tool.mypy]
strict = true
exclude = ["venv", "alembic"]
