"""Create legacy models

Revision ID: 24733bba2456
Revises: 1d08e35229d5
Create Date: 2024-05-22 23:22:55.656532

"""
import pgvector
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "24733bba2456"
down_revision = "1d08e35229d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector;"))
    op.create_table(
        "contentmetadata",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("codebase_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column(
            "content_type",
            sa.Enum(
                "SOURCE_CODE",
                "AUXILIARY_DOCUMENTATION",
                "FILE_SUMMARY",
                "FOLDER_SUMMARY",
                "CODE_SYMBOL",
                "UNKNOWN",
                name="contenttype",
            ),
            nullable=False,
        ),
        sa.Column("relative_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("misc_metadata", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contentmetadata_codebase_id"),
        "contentmetadata",
        ["codebase_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contentmetadata_relative_path"),
        "contentmetadata",
        ["relative_path"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contentmetadata_workspace_id"),
        "contentmetadata",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "derived_content_types",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("type_name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type_name"),
    )
    op.create_table(
        "llms",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("training_date", sa.Date(), nullable=False),
        sa.Column("model_owned_by", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtimelogagentinstance",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("codebase_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "setup_completed",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source_content_types",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("type_name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type_name"),
    )
    op.create_table(
        "workspaces",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chunk",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("content_metadata_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "text_embedding_3_small",
            pgvector.sqlalchemy.Vector(dim=1536),
            nullable=True,
        ),
        sa.Column("chunk_number", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_metadata_id"],
            ["contentmetadata.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "codebases",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("codebase_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "processing",
                "processing-complete",
                "processing-error",
                "codebase-rejected",
                name="enum_codebase_status",
            ),
            nullable=False,
        ),
        sa.Column("storage_url", sa.Text(), nullable=True),
        sa.Column("resource_root", sa.Text(), nullable=True),
        sa.Column("creator_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "codebase_name", name="uq_workspace_id_codebase_name"
        ),
    )
    op.create_table(
        "runtimelogagenterror",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("agent_instance_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_instance_id"],
            ["runtimelogagentinstance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtimelogagentmessage",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("message", sa.JSON(), nullable=False),
        sa.Column("order", sa.Integer(), autoincrement=True, nullable=True),
        sa.Column("agent_instance_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_instance_id"],
            ["runtimelogagentinstance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runtimelogcontentretrieval",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("agent_instance_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("chunk_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_instance_id"],
            ["runtimelogagentinstance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunk.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source_contents",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "source_content_type_id", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("codebase_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column("relative_path", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["codebase_id"],
            ["codebases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_content_type_id"],
            ["source_content_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "derived_contents",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "derived_content_type_id", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.Column("source_content_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("llm_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "generating",
                "generation-complete",
                "generation-error",
                name="enum_derived_content_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("order", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.ForeignKeyConstraint(
            ["derived_content_type_id"],
            ["derived_content_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["llm_id"],
            ["llms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_content_id"],
            ["source_contents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("derived_contents")
    op.drop_table("source_contents")
    op.drop_table("runtimelogcontentretrieval")
    op.drop_table("runtimelogagentmessage")
    op.drop_table("runtimelogagenterror")
    op.drop_table("codebases")
    op.drop_table("chunk")
    op.drop_table("workspaces")
    op.drop_table("source_content_types")
    op.drop_table("setup_completed")
    op.drop_table("runtimelogagentinstance")
    op.drop_table("llms")
    op.drop_table("derived_content_types")
    op.drop_index(op.f("ix_contentmetadata_workspace_id"), table_name="contentmetadata")
    op.drop_index(
        op.f("ix_contentmetadata_relative_path"), table_name="contentmetadata"
    )
    op.drop_index(op.f("ix_contentmetadata_codebase_id"), table_name="contentmetadata")
    op.drop_table("contentmetadata")
    # ### end Alembic commands ###
