[tool.poetry]
name = "mermaid-validator"
version = "0.1.0"
description = ""
authors = ["Neil Zumwalde <neilzumwalde@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
modal = "^1.0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
