"""
This module handles SNS events generated by uploads to pre-signed URLs in S3.
It processes the events, copies the documents to the appropriate S3 bucket,
and triggers the generation of PDF summaries for the uploaded documents.
"""

import json
import logging
import os
from pathlib import Path
from urllib.parse import unquote_plus
from uuid import UUID

import botocore
import httpx
from aws_secretsmanager_caching import SecretCache, SecretCacheConfig
from src.utils.aws_s3 import (
    copy_s3_object,
    ensure_bucket_exists,
    has_no_threats_tag,
    head_object,
)
from src.utils.config import settings

log_level = os.environ.get("LOG_LEVEL").upper() or logging.INFO
if len(logging.getLogger().handlers) > 0:
    # The Lambda environment pre-configures a handler logging to stderr. If a handler is already configured,
    # `.basicConfig` does not execute. Thus we set the level directly.
    logging.getLogger().setLevel(log_level)
else:
    logging.basicConfig(level=log_level)

logger = logging.getLogger()
logger.info(f"Log level set to {log_level}")


# # Python lambdas have to be synchronous ¯\_(ツ)_/¯
# # https://stackoverflow.com/questions/60455830/can-you-have-an-async-handler-in-lambda-python-3-6
def handler(event: dict, context: dict) -> any:
    logger.info(event)
    results = []

    for record in event["Records"]:
        sns_message = json.loads(record["Sns"]["Message"])

        sm_client = botocore.session.get_session().create_client(
            "secretsmanager",
            region_name="us-east-1",
        )
        cache_config = SecretCacheConfig()
        cache = SecretCache(config=cache_config, client=sm_client)

        client_id = (
            cache.get_secret_string(settings.CLIENT_ID_SECRET)
            if settings.ENVIRONMENT != "local"
            else settings.CLIENT_ID_SECRET
        )
        client_secret = (
            cache.get_secret_string(settings.CLIENT_SECRET_SECRET)
            if settings.ENVIRONMENT != "local"
            else settings.CLIENT_SECRET_SECRET
        )
        payload = json.dumps(
            {
                "client_id": client_id,
                "client_secret": client_secret,
                "audience": settings.API_URL,
                "grant_type": "client_credentials",
            }
        )

        with httpx.Client(base_url=settings.AUTH0_URL) as auth0Client:
            logger.info("Fetching M2M token from Auth0...")
            token_response = auth0Client.post(
                "/oauth/token",
                headers={"content-type": "application/json"},
                data=payload,
            )
            token_response.raise_for_status()
            token_json = token_response.json()

            logger.info("Processing S3 event(s)...")
            # Extract information from the S3 event
            for s3_record in sns_message["Records"]:
                bucket_name = s3_record["s3"]["bucket"]["name"]
                object_key = s3_record["s3"]["object"]["key"]
                real_object_key = unquote_plus(
                    object_key
                )  # Decode URL-encoded object key

                logger.info("key = " + real_object_key)
                logger.info("bucket = " + bucket_name)
                metadata = head_object(bucket=bucket_name, key=real_object_key)
                source_content_id = metadata["Metadata"]["source_content_id"]
                if has_no_threats_tag(bucket=bucket_name, key=real_object_key):
                    logger.info("No threats found, continuing document onboarding")
                    # Check if the destination bucket exists, and create it if it doesn't
                    bucket_exists = ensure_bucket_exists(
                        metadata["Metadata"]["org_bucket"], region="us-east-1"
                    )
                    logger.info(
                        f"Processing content created with ID:{source_content_id}"
                    )

                    if bucket_exists:
                        logger.info("Copying to organization bucket...")
                        destination_bucket_name = metadata["Metadata"]["org_bucket"]
                        real_file_name = Path(real_object_key).name
                        destination_real_object_key = f"documents/{real_file_name}"
                        object_copied = copy_s3_object(
                            source_bucket=bucket_name,
                            source_key=real_object_key,
                            dest_bucket=destination_bucket_name,
                            dest_key=destination_real_object_key,
                        )

                        if not object_copied:
                            logging.error(
                                f"Failed to copy object from {bucket_name} to {destination_bucket_name}"
                            )
                            raise Exception(
                                f"Failed to copy object from {bucket_name} to {destination_bucket_name}"
                            )

                        logger.info(
                            f"Triggering pdf summary generation for bucket = {destination_bucket_name}, key = {destination_real_object_key}"
                        )

                        pdf_summary_response = exec_generate_pdf_summaries(
                            {
                                "source_content_id": source_content_id,
                            },
                            token_json["access_token"],
                        )
                        results.append(
                            {
                                "source_content_id": source_content_id,
                                "bucket": destination_bucket_name,
                                "key": destination_real_object_key,
                                "pdf_summary_response": pdf_summary_response,
                            }
                        )
                else:
                    logger.error("GuardDuty Found something, removing PDF from DB.")
                    exec_remove_pdf_record(
                        source_content_id, token_json["access_token"]
                    )

    return results


def exec_generate_pdf_summaries(event: dict, token: str) -> str:
    with httpx.Client(base_url=settings.API_URL, follow_redirects=True) as driverClient:
        payload = {**event}
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
            "Authorization": f"Bearer {token}",
        }
        response = driverClient.post(
            "/onboarding/generate-pdf-summaries", headers=headers, json=payload
        )
        response.raise_for_status()
        event_response = response.json()
        logger.info(event_response)
        return event_response


def exec_remove_pdf_record(pdf_id: UUID, token: str) -> str:
    with httpx.Client(base_url=settings.API_URL, follow_redirects=True) as driverClient:
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
            "Authorization": f"Bearer {token}",
        }
        response = driverClient.delete(f"/content/{pdf_id!s}/", headers=headers)
        response.raise_for_status()
        event_response = response.json()
        logger.info(event_response)
        return event_response
