"""
This module handles SNS events generated by uploads to pre-signed URLs in S3.
It processes the events, copies the documents to the appropriate S3 bucket,
and triggers the generation of PDF summaries for the uploaded documents.
"""
import json
import logging
from pathlib import Path
from urllib.parse import unquote_plus

import botocore
import botocore.session
import httpx
from aws_secretsmanager_caching import SecretCache, SecretCacheConfig
from src.utils.aws_s3 import copy_s3_object, ensure_bucket_exists, head_object
from src.utils.config import settings


# # Python lambdas have to be synchronous ¯\_(ツ)_/¯
# # https://stackoverflow.com/questions/60455830/can-you-have-an-async-handler-in-lambda-python-3-6
def handler(event, context):
    logging.info(event)
    results = []

    for record in event["Records"]:
        sns_message = json.loads(record["Sns"]["Message"])

        sm_client = botocore.session.get_session().create_client(
            "secretsmanager",
            region_name="us-east-1",
        )
        cache_config = SecretCacheConfig()
        cache = SecretCache(config=cache_config, client=sm_client)

        client_id = (
            cache.get_secret_string(settings.CLIENT_ID_SECRET)
            if settings.ENVIRONMENT != "local"
            else settings.CLIENT_ID_SECRET
        )
        client_secret = (
            cache.get_secret_string(settings.CLIENT_SECRET_SECRET)
            if settings.ENVIRONMENT != "local"
            else settings.CLIENT_SECRET_SECRET
        )
        payload = json.dumps(
            {
                "client_id": client_id,
                "client_secret": client_secret,
                "audience": settings.API_URL,
                "grant_type": "client_credentials",
            }
        )

        with httpx.Client(base_url=settings.AUTH0_URL) as auth0Client:
            logging.info("Fetching M2M token from Auth0...")
            token_response = auth0Client.post(
                "/oauth/token",
                headers={"content-type": "application/json"},
                data=payload,
            )
            token_response.raise_for_status()
            token_json = token_response.json()

        logging.info("Processing S3 event(s)...")
        # Extract information from the S3 event
        for s3_record in sns_message["Records"]:
            bucket_name = s3_record["s3"]["bucket"]["name"]
            object_key = s3_record["s3"]["object"]["key"]
            real_object_key = unquote_plus(object_key)  # Decode URL-encoded object key

            logging.info("key = " + real_object_key)
            logging.info("bucket = " + bucket_name)
            metadata = head_object(bucket=bucket_name, key=real_object_key)
            # Check if the destination bucket exists, and create it if it doesn't
            bucket_exists = ensure_bucket_exists(
                metadata["Metadata"]["org_bucket"], region="us-east-1"
            )
            source_content_id = metadata["Metadata"]["source_content_id"]
            logging.info(f"Processing content created with ID:{source_content_id}")

            if bucket_exists:
                logging.info("Copying to organization bucket...")
                destination_bucket_name = metadata["Metadata"]["org_bucket"]
                real_file_name = Path(real_object_key).name
                destination_real_object_key = f"documents/{real_file_name}"
                object_copied = copy_s3_object(
                    source_bucket=bucket_name,
                    source_key=real_object_key,
                    dest_bucket=destination_bucket_name,
                    dest_key=destination_real_object_key,
                )

                if not object_copied:
                    logging.error(
                        f"Failed to copy object from {bucket_name} to {destination_bucket_name}"
                    )
                    raise Exception(
                        f"Failed to copy object from {bucket_name} to {destination_bucket_name}"
                    )

                logging.info(
                    f"Triggering pdf summary generation for bucket = {destination_bucket_name}, key = {destination_real_object_key}"
                )

                pdf_summary_response = exec_generate_pdf_summaries(
                    {
                        "source_content_id": source_content_id,
                    },
                    token_json["access_token"],
                )
                results.append(
                    {
                        "source_content_id": source_content_id,
                        "bucket": destination_bucket_name,
                        "key": destination_real_object_key,
                        "pdf_summary_response": pdf_summary_response,
                    }
                )

    return results


def exec_generate_pdf_summaries(event: dict, token: str):
    with httpx.Client(base_url=settings.API_URL, follow_redirects=True) as driverClient:
        payload = {**event}
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
            "Authorization": f"Bearer {token}",
        }
        response = driverClient.post(
            "/onboarding/generate-pdf-summaries", headers=headers, json=payload
        )
        response.raise_for_status()
        event_response = response.json()
        logging.info(event_response)

        return "OK"
