[project]
name = "auth0-sync"
version = "0.1.0"
description = ""
authors = [
    {name = "Andrew Mark",email = "andrewemark@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.13"

[tool.poetry.dependencies]
database = {path = "../../driver_db", develop = true}
shared = {path = "../../packages/shared", develop = true}
modal = "^1.0.4"

[tool.poetry]
packages = [
    {include = "auth0_sync", from = "src"},
    {include = "event_processor", from = "src"}
]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
