"""migrate the node data

Revision ID: 1994cd6955b2
Revises: 3ad0719e3e4c
Create Date: 2024-12-23 14:37:24.964635

"""

from alembic import op
from database.nodes_data_migration_sql import (
    CODEBASE_TO_PRIMARY_ASSET_SQL,
    CODEBASE_TO_VERSION_SQL,
    DIRECTORIES_TO_NODE_SQL,
    FILES_TO_NODE_SQL,
    PAGE_TEMPLATES_TO_NODE_SQL,
    PAGE_TEMPLATES_TO_PRIMARY_ASSET_SQL,
    PAGE_TEMPLATES_TO_VERSION_SQL,
    PAGES_TO_NODE_SQL,
    PAGES_TO_PRIMARY_ASSET_SQL,
    PAGES_TO_VERSION_SQL,
    PDF_TO_NODE_SQL,
    PDF_TO_PRIMARY_ASSET_SQL,
    PDF_TO_VERSION_SQL,
    UPDATE_NODE_ID_APPLICATION_NOTE_SQL,
    UPDATE_NODE_ID_CODEBASE_SQL,
    UPDATE_NODE_ID_NON_STANDARD_SQL,
)

# revision identifiers, used by Alembic.
revision = "1994cd6955b2"
down_revision = "3ad0719e3e4c"
branch_labels = None
depends_on = None


def upgrade():  # ignore: ANN201
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###

    print("Migrating all nodes for CODEBASES")

    op.execute(CODEBASE_TO_PRIMARY_ASSET_SQL)
    print("Executed CODEBASE_TO_PRIMARY_ASSET_SQL")

    op.execute(CODEBASE_TO_VERSION_SQL)
    print("Executed CODEBASE_TO_VERSION_SQL")

    op.execute(DIRECTORIES_TO_NODE_SQL)
    print("Executed DIRECTORIES_TO_NODE_SQL")

    op.execute(FILES_TO_NODE_SQL)
    print("Executed FILES_TO_NODE_SQL")

    op.execute(PDF_TO_PRIMARY_ASSET_SQL)
    print("Executed PDF_TO_PRIMARY_ASSET_SQL")

    op.execute(PDF_TO_VERSION_SQL)
    print("Executed PDF_TO_VERSION_SQL")

    op.execute(PDF_TO_NODE_SQL)
    print("Executed PDF_TO_NODE_SQL")

    op.execute(PAGES_TO_PRIMARY_ASSET_SQL)
    print("Executed PAGES_TO_PRIMARY_ASSET_SQL")

    op.execute(PAGES_TO_VERSION_SQL)
    print("Executed PAGES_TO_VERSION_SQL")

    op.execute(PAGES_TO_NODE_SQL)
    print("Executed PAGES_TO_NODE_SQL")

    op.execute(PAGE_TEMPLATES_TO_PRIMARY_ASSET_SQL)
    print("Executed PAGE_TEMPLATES_TO_PRIMARY_ASSET_SQL")

    op.execute(PAGE_TEMPLATES_TO_VERSION_SQL)
    print("Executed PAGE_TEMPLATES_TO_VERSION_SQL")

    op.execute(PAGE_TEMPLATES_TO_NODE_SQL)
    print("Executed PAGE_TEMPLATES_TO_NODE_SQL")

    op.execute(UPDATE_NODE_ID_NON_STANDARD_SQL)
    print("Executed UPDATE_NODE_ID_NON_STANDARD_SQL")

    op.execute(UPDATE_NODE_ID_APPLICATION_NOTE_SQL)
    print("Executed UPDATE_NODE_ID_APPLICATION_NOTE_SQL")

    op.execute(UPDATE_NODE_ID_CODEBASE_SQL)
    print("Executed UPDATE_NODE_ID_CODEBASE_SQL")


def downgrade():  # ignore: ANN201
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
