"""add nodes

Revision ID: 911af6a98754
Revises: 1475962b9869
Create Date: 2024-12-03 16:05:08.438880

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from database.nodes_data_migration_sql import (
    CODEBASE_TO_PRIMARY_ASSET_SQL,
    CODEBASE_TO_VERSION_SQL,
    DIRECTORIES_TO_NODE_SQL,
    FILES_TO_NODE_SQL,
    PAGE_TEMPLATES_TO_NODE_SQL,
    PAGE_TEMPLATES_TO_PRIMARY_ASSET_SQL,
    PAGE_TEMPLATES_TO_VERSION_SQL,
    PAGES_TO_NODE_SQL,
    PAGES_TO_PRIMARY_ASSET_SQL,
    PAGES_TO_VERSION_SQL,
    PDF_TO_NODE_SQL,
    PDF_TO_PRIMARY_ASSET_SQL,
    PDF_TO_VERSION_SQL,
    UPDATE_NODE_ID_APPLICATION_NOTE_SQL,
    UPDATE_NODE_ID_CODEBASE_SQL,
    UPDATE_NODE_ID_NON_STANDARD_SQL,
    UPDATE_content_kind_SQL,
)

# revision identifiers, used by Alembic.
revision = "911af6a98754"
down_revision = "1475962b9869"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "v2_primary_asset",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "primary_asset_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("repository_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_v2_primary_asset_organization_id_display_name",
        "v2_primary_asset",
        ["organization_id", "display_name"],
        unique=True,
    )
    op.create_table(
        "v2_version",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("primary_asset_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["primary_asset_id"], ["v2_primary_asset.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_v2_version_primary_asset_id_display_name",
        "v2_version",
        ["primary_asset_id", "display_name"],
        unique=True,
    )
    op.create_table(
        "v2_node",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("relative_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "misc_metadata",
            sa.JSON(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["version_id"], ["v2_version.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_version_id_relative_path",
        "v2_node",
        ["version_id", "relative_path"],
        unique=True,
    )

    op.add_column("derived_contents", sa.Column("node_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_derived_contents_node_id"),
        "derived_contents",
        ["node_id"],
        unique=False,
    )
    op.create_foreign_key(None, "derived_contents", "v2_node", ["node_id"], ["id"])
    op.add_column(
        "derived_contents",
        sa.Column("content_kind", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_index(
        op.f("ix_derived_contents_content_kind"),
        "derived_contents",
        ["content_kind"],
        unique=False,
    )
    op.create_table(
        "v2_primary_asset_tag",
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column("primary_asset_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"]),
        sa.ForeignKeyConstraint(["primary_asset_id"], ["v2_primary_asset.id"]),
        sa.PrimaryKeyConstraint("tag_id", "primary_asset_id"),
    )
    op.alter_column(
        "derived_contents", "content_type_id", existing_type=sa.Uuid(), nullable=True
    )
    op.alter_column(
        "derived_contents", "workspace_id", existing_type=sa.Uuid(), nullable=True
    )
    op.alter_column(
        "derived_contents", "codebase_id", existing_type=sa.Uuid(), nullable=True
    )
    op.execute("""
            CREATE VIEW v2_full_node AS
            SELECT
                pa.id AS primary_asset_id,
                pa.display_name AS primary_asset_display_name,
                pa.organization_id AS primary_asset_organization_id,
                pa.created_at AS primary_asset_created_at,
                pa.updated_at AS primary_asset_updated_at,
                pa.primary_asset_type AS primary_asset_primary_asset_type,
                v.id AS version_id,
                v.display_name AS version_display_name,
                v.created_at AS version_created_at,
                v.updated_at AS version_updated_at,
                n.id AS node_id,
                n.relative_path AS node_relative_path,
                n.created_at AS node_created_at,
                n.updated_at AS node_updated_at
            FROM
                v2_primary_asset pa
            LEFT JOIN
                v2_version v ON pa.id = v.primary_asset_id
            LEFT JOIN
                v2_node n ON v.id = n.version_id
               """)

    print("Executing: Update derived_contents with content_kind")
    op.execute(UPDATE_content_kind_SQL)

    # MIGRATE CODEBASES

    op.execute(CODEBASE_TO_PRIMARY_ASSET_SQL)

    op.execute(CODEBASE_TO_VERSION_SQL)

    # NOTE: The root node is the lowest level directory, which exists with the same relative path as the codebase currently.
    # op.execute(DIRECTORIES_TO_NODE_SQL)

    print("Executing: SOURCE CONTENT [Directories] -> NODE")
    op.execute(DIRECTORIES_TO_NODE_SQL)

    print("Executing: SOURCE CONTENT [Files] -> NODE")
    op.execute(FILES_TO_NODE_SQL)

    # MIGRATE PDFs

    print("Executing: PDF -> PRIMARY ASSET")
    op.execute(PDF_TO_PRIMARY_ASSET_SQL)

    print("Executing: PDF -> VERSION")
    op.execute(PDF_TO_VERSION_SQL)

    print("Executing: SOURCE CONTENT [PDF] -> NODE")
    op.execute(PDF_TO_NODE_SQL)

    # MIGRATE PAGES

    print("Executing: PAGES -> PRIMARY ASSET")
    op.execute(PAGES_TO_PRIMARY_ASSET_SQL)

    print("Executing: PAGES -> VERSION")
    op.execute(PAGES_TO_VERSION_SQL)

    print("Executing: SOURCE CONTENT [PAGES] -> NODE")
    op.execute(PAGES_TO_NODE_SQL)

    # MIGRATE PAGE TEMPLATES

    print("Executing: PAGE TEMPLATES -> PRIMARY ASSET")
    op.execute(PAGE_TEMPLATES_TO_PRIMARY_ASSET_SQL)

    print("Executing: PAGE TEMPLATES -> VERSION")
    op.execute(PAGE_TEMPLATES_TO_VERSION_SQL)

    print("Executing: SOURCE CONTENT [PAGE TEMPLATES] -> NODE")
    op.execute(PAGE_TEMPLATES_TO_NODE_SQL)

    print("Executing: Update derived_contents with node_id for non-standard types")
    op.execute(UPDATE_NODE_ID_NON_STANDARD_SQL)

    print("Executing: Update derived_contents with node_id for application_note")
    op.execute(UPDATE_NODE_ID_APPLICATION_NOTE_SQL)

    print("Executing: Update derived_contents with node_id for codebase")
    op.execute(UPDATE_NODE_ID_CODEBASE_SQL)
    # ### end Alembic commands ###


def downgrade() -> None:
    print("Executing: DROP TABLE v2_primary_asset_tags")
    op.drop_table("v2_primary_asset_tag")
    # ### commands auto generated by Alembic - please adjust! ###
    print("Executing: DROP VIEW IF EXISTS v2_full_node")
    op.execute("DROP VIEW IF EXISTS v2_full_node")

    print("Executing: DROP INDEX ix_derived_contents_node_id on derived_contents")
    op.drop_index(op.f("ix_derived_contents_node_id"), table_name="derived_contents")

    print("Executing: DROP INDEX ix_derived_contents_content_kind on derived_contents")
    op.drop_index(
        op.f("ix_derived_contents_content_kind"), table_name="derived_contents"
    )

    print("Executing: DROP COLUMN content_kind from derived_contents")
    op.drop_column("derived_contents", "content_kind")

    print("Executing: DROP COLUMN node_id from derived_contents")
    op.drop_column("derived_contents", "node_id")

    print("Executing: DROP INDEX ix_version_id_relative_path on v2_node")
    op.drop_index("ix_version_id_relative_path", table_name="v2_node")

    print("Executing: DROP TABLE v2_node")
    op.drop_table("v2_node")

    print(
        "Executing: DROP INDEX ix_v2_version_primary_asset_id_display_name on v2_version"
    )
    op.drop_index(
        "ix_v2_version_primary_asset_id_display_name", table_name="v2_version"
    )

    print("Executing: DROP TABLE v2_version")
    op.drop_table("v2_version")

    print(
        "Executing: DROP INDEX ix_v2_primary_asset_organization_id_display_name on v2_primary_asset"
    )
    op.drop_index(
        "ix_v2_primary_asset_organization_id_display_name",
        table_name="v2_primary_asset",
    )

    print("Executing: DROP TABLE v2_primary_asset")
    op.drop_table("v2_primary_asset")

    # ### end Alembic commands ###
