[tool.poetry]
name = "embedding"
version = "0.1.0"
description = ""
authors = ["Neil Zumwalde <neilzumwalde@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
shared = {path = "../../packages/shared", develop = true}
modal = "^0.63.92"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
