import asyncio
import subprocess
import tempfile
from enum import StrEnum
from pathlib import Path

from aiolimiter import AsyncLimiter
from onboarding import bitbucket_ops, gh_ops, gitlab_ops
from pydantic import BaseModel
from shared.agent.chat_openai_async import ChatOpenAI, OutputConfig, OutputConfigKind
from shared.prompts.structured_prompting import (
    GENERAL_STE_STYLE_INSTRUCTION,
    Component,
    Prompt,
)
from tqdm.asyncio import tqdm_asyncio
from utils.git_fetcher_pygit2 import CommitData, GitFetcher

MAX_COMMITS_TO_PROCESS = 2500


class CommitType(StrEnum):
    feature = "feature"
    bugfix = "bugfix"
    refactor = "refactor"
    chore = "chore"
    docs = "docs"
    test = "test"
    performance = "performance"
    style = "style"
    build = "build"
    other = "other"


class CommitSummary(BaseModel):
    summary: str
    type: CommitType


OPENAI_SEM = asyncio.Semaphore(75)
OPENAI_LIMITER = AsyncLimiter(25, 1)  # 25 requests per second

system_prompt = """
You are a meticulous software development assistant. Your task is to summarize code changes in a clear and concise way, based on both the commit message and the actual code diff.

Your summary should:
- Reflect what the commit **actually does**, not just what the message claims.
- Include the **type of change** (e.g., feature, bugfix, refactor, test addition, performance improvement).
- Highlight **key files or functions** modified if they are relevant to understanding the change.
- Be written in natural language that could be used in a changelog, code review, or documentation.

Provide the summary in 1 paragraph. Be sure to highlight any major features added, bugs fixed, or significant refactors. If the commit is a minor change or typo fix, note that as well.
"""
user_prompt_template = """
Summarize the following commit. Use both the commit message and the diff to produce a meaningful description of what changed and why.

### Commit Message
{commit_message}

### Diff
{commit_diff}
"""

changelog_system_prompt = (
    Prompt.empty()
    .append(
        Component(
            string="""
    You are a changelog aggregation assistant.

    You will receive a set of commit summaries generated by another model. Your task is to:

    1. Organize entries under standardized categories:
    - Features - Break down new features into sub-sections that describe the feature with 1-5 bullet points. Include any major refactors here.
    - Bug Fixes - A list of no more than 3-5 important bug fixes.
    - Ignore other types of changes. DO NOT list chores, documentation changes, or testing updates.
    2. **Deduplicate or merge** similar entries (e.g., multiple commits that add a similar feature or fix related issues).
    3. **Clean up language** to be clear, human-readable, and professional. Do not include file paths or commit hashes, describe the features in human readable language. You should reference important code entities as needed though.

    Use a clean Markdown format for the final output, suitable for inclusion in a `CHANGELOG.md` file.

    IMPORTANT INSTRUCTIONS:
    - DO NOT include any commit hashes or file paths in the final output.
    - DO NOT list more than 3-5 bugs in the Bug Fixes section
    - DO NOT describe minor refactors or changes that do not significantly impact the codebase.
    - DO NOT include any personal opinions or subjective language.
    - DO ignore other types of changes like chores, documentation updates, or testing changes.
    - DO summarize features in 1-5 bullet points, focusing on the key aspects of the feature.

    DO NOT summarize or conclude the changelog, just provide the changelog information as is.
    """
        )
    )
    .append(GENERAL_STE_STYLE_INSTRUCTION)
    .into_str()
)

overall_changelog_system_prompt = """
You are a structured summarization agent tasked with generating a one-page historical timeline of a software codebase. Your output will be consumed by other LLM-based agents via an MCP server to reason about feature history, architectural shifts, and capability evolution.

You will read detailed changelogs or release notes and extract high-signal, chronologically ordered entries.

Your output must:

- Be in valid **YAML**. With a top-level key `changelog` that contains a list of entries.
- Each entry should describe a month and may contain up to 5 tightly written bullet points.
- Each bullet should:
  - Begin with a **strong action verb** (e.g., Introduced, Refactored, Migrated)
  - Reference the **feature, subsystem, or outcome**
  - Be **atomic**, avoiding pronouns and vague references
- Avoid opinion, commentary, or duplication

Do not include explanation, comments, or any markdown — output only the YAML block.

An example output format is:
```yaml
changelog:
  - 2024-01:
      - Introduced a new user authentication system with OAuth2 support
      - Refactored the payment processing module to improve performance
      - Migrated the database to PostgreSQL for better scalability
  - 2024-02:
      - Added a new feature for real-time notifications
      - Fixed critical bugs in the user profile management system
      - Improved test coverage across the codebase
```
"""


async def llm_generate(
    llm: ChatOpenAI, system_prompt: str, user_prompt: str, config: OutputConfig
) -> str:
    async with OPENAI_SEM, OPENAI_LIMITER:
        if len(user_prompt) > 250000:
            print("Long user prompt detected, truncating to 250000 characters.")
            user_prompt = user_prompt[:250000]  # Truncate to avoid issues
        return await llm.generate_response(
            system_prompt=system_prompt, user_prompt=user_prompt, output_cfg=config
        )


async def summarize_commits(
    commits: list[CommitData],
) -> dict[str, CommitSummary]:  # {sha: summary}
    llm = ChatOpenAI(model="gpt-4.1", temperature=0.0, request_timeout=120)
    summarized_commits = {}  # {sha: summary}
    sha_list = []
    task_coroutines = []
    for commit in commits:
        sha_list.append(commit.sha)
        user_prompt = user_prompt_template.format(
            commit_message=commit.message, commit_diff=commit.diff
        )
        config = OutputConfig(kind=OutputConfigKind.JSON_STRICT, payload=CommitSummary)
        task_coroutines.append(llm_generate(llm, system_prompt, user_prompt, config))
    task_results = await tqdm_asyncio.gather(*task_coroutines)

    for sha, result in zip(sha_list, task_results):
        parsed_response = CommitSummary.parse_raw(result)
        summarized_commits[sha] = parsed_response
    return summarized_commits


async def make_monthly_changelog(
    all_commits: list[CommitData],
    commit_summaries: dict[str, CommitSummary],
) -> dict[str, str]:
    model = ChatOpenAI(
        model="o3-mini",
        temperature=0.0,
        request_timeout=400,
    )

    commit_prompt_by_month = {}

    for commit in all_commits:
        month_key = commit.authored_date.strftime("%Y-%m")
        if month_key not in commit_prompt_by_month:
            commit_prompt_by_month[month_key] = ""

        commit_prompt_by_month[month_key] += (
            f"**{commit.sha}**: {commit_summaries[commit.sha].summary} (Type: {commit_summaries[commit.sha].type})\n\n"
        )

    aggregated_results = {}  # {month_key: str}
    task_coroutines = []
    for month_key, commit_prompt in commit_prompt_by_month.items():
        user_prompt = f"### Commits for {month_key}\n{commit_prompt}"
        config = OutputConfig(
            kind=OutputConfigKind.TEXT,
        )
        task_coroutines.append(
            llm_generate(model, changelog_system_prompt, user_prompt, config)
        )

    aggregated_results = await tqdm_asyncio.gather(*task_coroutines)
    monthly_summaries = {}
    for month_key, result in zip(commit_prompt_by_month.keys(), aggregated_results):
        monthly_summaries[month_key] = result

    return monthly_summaries


async def generate_overall_changelog(
    monthly_changelogs: dict[str, str],
) -> str:
    overall_changelog_model = ChatOpenAI(
        model="o3-mini",
        temperature=0.0,
        request_timeout=600,
    )

    overall_changelog_user_prompt = ""
    for month_key, result in monthly_changelogs.items():
        overall_changelog_user_prompt += f"### Changelog for {month_key}\n{result}\n"

    overall_changelog_config = OutputConfig(
        kind=OutputConfigKind.TEXT,
    )
    overall_changelog_result = await llm_generate(
        overall_changelog_model,
        overall_changelog_system_prompt,
        overall_changelog_user_prompt,
        overall_changelog_config,
    )
    return overall_changelog_result


async def create_changelog(
    version_id: str,
    install_id: str,
) -> dict:
    from database.db import engine
    from database.models import GitProviderAppInstallation
    from database.models_enums import PrimaryAssetProvider
    from sqlmodel import Session, select
    from utils.db import get_version_by_id, git_provider_app_installation_by_id

    version = await get_version_by_id(version_id)
    repo_id = version.primary_asset.repository_id
    repo_name = version.primary_asset.display_name
    provider = version.primary_asset.provider

    if provider == PrimaryAssetProvider.GITHUB:
        access_token = gh_ops.fetch_app_access_token(install_id)
        clone_url, full_name = gh_ops.get_repo_clone_info_from_id(repo_id, access_token)
    elif provider == PrimaryAssetProvider.BITBUCKET:
        access_token = bitbucket_ops.fetch_access_token(install_id)
        gp_install = git_provider_app_installation_by_id(installation_id=install_id)
        workspace = gp_install.git_provider_app.provider_metadata["workspace"]
        repo_slug = version.primary_asset.display_name
        # Bitbucket allows spaces in repo names, but does not URL encode them
        # and instead replaces them with hyphens.
        # We need to replace spaces with hyphens in the repo name.
        repo_slug = "-".join(repo_name.split())  # multiple spaces go to single hyphen

        clone_url, full_name = bitbucket_ops.get_repo_clone_info_from_id(
            workspace, repo_slug, access_token
        )
    elif provider == PrimaryAssetProvider.GITLAB_SELF_MANAGED:
        with Session(engine) as session:
            installation_id = version.primary_asset.installation_id
            app_install = session.exec(
                select(GitProviderAppInstallation).where(
                    GitProviderAppInstallation.id == installation_id
                )
            ).one()
            if app_install is None:
                raise ValueError(f"Installation ID {installation_id} not found.")
            base_url = app_install.git_provider_app.base_url
        access_token = gitlab_ops.fetch_access_token(install_id)
        clone_url, full_name = gitlab_ops.get_repo_clone_info_from_id(
            base_url, repo_id, access_token
        )
    else:
        raise ValueError(f"Unsupported provider: {provider}")

    with tempfile.TemporaryDirectory() as temp_dir:
        repo_dir = Path(temp_dir) / full_name
        result = subprocess.run(
            f"git clone {clone_url} {repo_dir}",
            shell=True,
            cwd=None,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise subprocess.CalledProcessError(
                result.returncode, f"git clone {clone_url} {repo_dir}"
            )

        repo = GitFetcher(repo_path=repo_dir)
        all_commits = list(repo.fetch_commits(limit=MAX_COMMITS_TO_PROCESS))
        print(f"Fetched {len(all_commits)} commits from {full_name}")
        if not all_commits:
            print("No commits found, skipping changelog generation.")
            return {}

        summarized_commits = await summarize_commits(all_commits)
        monthly_changelogs = await make_monthly_changelog(
            all_commits, summarized_commits
        )
        overall_changelog = await generate_overall_changelog(monthly_changelogs)

        return {
            "monthly_changelogs": monthly_changelogs,
            "overall_changelog": overall_changelog,
        }
