"""init

Revision ID: c2ec175264a8
Revises:
Create Date: 2024-02-16 09:11:29.781054

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2ec175264a8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector;"))
    op.create_table(
        "contentprocessingsession",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("code_revision", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("arguments", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contentmetadata",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("codebase_id", sqlmodel.sql.sqltypes.GUID(), nullable=True),
        sa.Column(
            "content_type",
            sa.Enum(
                "SOURCE_CODE",
                "AUXILIARY_DOCUMENTATION",
                "FILE_SUMMARY",
                "UNKNOWN",
                name="contenttype",
            ),
            nullable=False,
        ),
        sa.Column("relative_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("misc_metadata", sa.JSON(), nullable=False),
        sa.Column(
            "content_processing_session_id", sqlmodel.sql.sqltypes.GUID(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["content_processing_session_id"],
            ["contentprocessingsession.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contentmetadata_codebase_id"),
        "contentmetadata",
        ["codebase_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contentmetadata_relative_path"),
        "contentmetadata",
        ["relative_path"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contentmetadata_workspace_id"),
        "contentmetadata",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "chunk",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("content_metadata_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "text_embedding_3_small",
            pgvector.sqlalchemy.Vector(dim=1536),
            nullable=True,
        ),
        sa.Column("chunk_number", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["content_metadata_id"],
            ["contentmetadata.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chunk")
    op.drop_index(op.f("ix_contentmetadata_workspace_id"), table_name="contentmetadata")
    op.drop_index(
        op.f("ix_contentmetadata_relative_path"), table_name="contentmetadata"
    )
    op.drop_index(op.f("ix_contentmetadata_codebase_id"), table_name="contentmetadata")
    op.drop_table("contentmetadata")
    op.drop_table("contentprocessingsession")
    # ### end Alembic commands ###
