"""add token_count

Revision ID: d62236745250
Revises: 53972ce88dff
Create Date: 2024-03-01 14:53:30.821937

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d62236745250"
down_revision: Union[str, None] = "53972ce88dff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chunk", sa.Column("token_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chunk", "token_count")
    # ### end Alembic commands ###
