"""make workspaceid nullable on AgentLog and add org

Revision ID: 30cdf7ecd07a
Revises: 8cdbf2c4608d
Create Date: 2024-08-22 12:32:19.700862

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "30cdf7ecd07a"
down_revision = "8cdbf2c4608d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "runtimelogagentinstance",
        sa.Column("organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )

    # Set the default organization_id based on the current organization_id of the workspace
    op.execute(
        """
        UPDATE runtimelogagentinstance
        SET organization_id = (
            SELECT organization_id
            FROM workspaces
            WHERE workspaces.id = runtimelogagentinstance.workspace_id::uuid
        )
    """
    )

    # Alter the column to make it non-nullable after setting the default values
    op.alter_column("runtimelogagentinstance", "organization_id", nullable=False)
    op.alter_column(
        "runtimelogagentinstance",
        "workspace_id",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "runtimelogagentinstance",
        "workspace_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.drop_column("runtimelogagentinstance", "organization_id")
    # ### end Alembic commands ###
