"""Add versioning

Revision ID: fd35c6bb56dc
Revises: 825dd67423b0
Create Date: 2024-10-31 10:50:41.318145

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fd35c6bb56dc"
down_revision = "825dd67423b0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inspection_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("previous_version_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["previous_version_id"],
            ["inspection_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inspectorrun",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("inspection_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["inspection_version_id"],
            ["inspection_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("chunkandembedding", "__ts_vector__")
    op.add_column("derived_contents", sa.Column("version_id", sa.Uuid(), nullable=True))
    op.drop_index("ix_derived_contents_content_name", table_name="derived_contents")
    op.create_index(
        op.f("ix_derived_contents_version_id"),
        "derived_contents",
        ["version_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "derived_contents", "inspection_versions", ["version_id"], ["id"]
    )
    op.drop_index("ix_tag_type", table_name="tags")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_tag_type", "tags", ["type"], unique=False)
    op.drop_constraint(None, "derived_contents", type_="foreignkey")
    op.drop_index(op.f("ix_derived_contents_version_id"), table_name="derived_contents")
    op.create_index(
        "ix_derived_contents_content_name",
        "derived_contents",
        ["content_name"],
        unique=False,
    )
    op.drop_column("derived_contents", "version_id")
    op.add_column(
        "chunkandembedding",
        sa.Column(
            "__ts_vector__",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english'::regconfig, (text)::text)", persisted=True
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_table("inspectorrun")
    op.drop_table("inspection_versions")
    # ### end Alembic commands ###
