"""add tsvector to v2

Revision ID: 8ec222d15db9
Revises: 9e2ced247f0c
Create Date: 2024-11-19 14:33:21.510253

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "8ec222d15db9"
down_revision = "9e2ced247f0c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_chunkandembedding___ts_vector__",
        "chunkandembedding",
        ["__ts_vector__"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_chunkandembedding___ts_vector__",
        "v2_chunk",
        ["__ts_vector__"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_chunkandembedding___ts_vector__",
        table_name="v2_chunk",
        postgresql_using="gin",
    )
    op.drop_index(
        "ix_chunkandembedding___ts_vector__",
        table_name="chunkandembedding",
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
