"""Add user table

Revision ID: a5b7f7a95a7d
Revises: 78084f9c296b
Create Date: 2024-11-22 15:36:27.465875

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "a5b7f7a95a7d"
down_revision = "78084f9c296b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "github_app_installation_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "organization_id", name="uq_user_org"),
    )
    op.create_index(
        op.f("ix_user_github_app_installation_id"),
        "user",
        ["github_app_installation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_user_user_id"), "user", ["user_id"], unique=False)
    op.create_index(
        "uq_installation_id_non_null",
        "user",
        ["github_app_installation_id"],
        unique=True,
        postgresql_where=sa.text("github_app_installation_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_installation_id_non_null",
        table_name="user",
    )
    op.drop_index(op.f("ix_user_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_github_app_installation_id"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
