"""Add usage plan and subscription tables

Revision ID: 0c68acd8a447
Revises: 86ed58d5305f
Create Date: 2024-12-10 14:23:17.306298

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "0c68acd8a447"
down_revision = "86ed58d5305f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("base_usage_price", sa.Float(), nullable=False),
        sa.Column("base_seat_price", sa.Float(), nullable=False),
        sa.Column(
            "billing_frequency", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plan_name"), "plan", ["name"], unique=False)
    op.create_table(
        "subscription",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "TRIAL",
                "PAST_DUE",
                "CANCELED",
                "SUSPENDED",
                name="subscriptionstatus",
            ),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "billing_frequency", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscription_organization_id"),
        "subscription",
        ["organization_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_subscription_plan_id"), "subscription", ["plan_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_plan_id"), table_name="subscription")
    op.drop_index(op.f("ix_subscription_organization_id"), table_name="subscription")
    op.drop_table("subscription")
    op.drop_index(op.f("ix_plan_name"), table_name="plan")
    op.drop_table("plan")
    op.execute("DROP TYPE IF EXISTS subscriptionstatus")
    # ### end Alembic commands ###
