"""Add usage tracking tables

Revision ID: 2b02b2d6c98b
Revises: fd35c6bb56dc
Create Date: 2024-11-05 13:03:05.302071

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2b02b2d6c98b"
down_revision = "fd35c6bb56dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usage_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "RUNNING", "COMPLETED", "FAILED", name="usagesessionstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_usage_sessions_status"), "usage_sessions", ["status"], unique=False
    )
    op.create_table(
        "usage_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "ap_debit",
                "td_debit",
                "cd_debit",
                "ob_debit",
                "su_debit",
                "bp_credit",
                "adt_credit",
                name="usageeventtype",
            ),
            nullable=False,
        ),
        # sa.Column('event_type', sa.Enum('AGENT_PIPELINE_USAGE_DEBIT', 'INSPECTOR_TECH_DOC_USAGE_DEBIT', 'INSPECTOR_CODE_DIFF_USAGE_DEBIT', 'ONBOARDING_USAGE_DEBIT', 'SUMMARIZATION_USAGE_DEBIT', 'BASE_PLATFORM_USAGE_CREDIT', 'ADDITIONAL_PLATFORM_USAGE_CREDIT', name='usageeventtype'), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column(
            "organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("event_source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bytes_in", sa.Integer(), nullable=False),
        sa.Column("bytes_out", sa.Integer(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"], ["usage_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_usage_events_event_type"), "usage_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_usage_events_session_id"), "usage_events", ["session_id"], unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_usage_events_session_id"), table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_event_type"), table_name="usage_events")
    op.drop_table("usage_events")
    op.drop_index(op.f("ix_usage_sessions_status"), table_name="usage_sessions")
    op.drop_table("usage_sessions")
    op.execute("DROP TYPE IF EXISTS usagesessionstatus")
    op.execute("DROP TYPE IF EXISTS usageeventtype")
    # ### end Alembic commands ###
