"""add nodes

Revision ID: 911af6a98754
Revises: 78084f9c296b
Create Date: 2024-12-03 16:05:08.438880

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "911af6a98754"
down_revision = "78084f9c296b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "v2_primary_asset",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "organization_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "primary_asset_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_v2_primary_asset_organization_id_display_name",
        "v2_primary_asset",
        ["organization_id", "display_name"],
        unique=True,
    )
    op.create_table(
        "v2_version",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("primary_asset_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["primary_asset_id"], ["v2_primary_asset.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_v2_version_primary_asset_id_display_name",
        "v2_version",
        ["primary_asset_id", "display_name"],
        unique=True,
    )
    op.create_table(
        "v2_node",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("relative_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["version_id"], ["v2_version.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_version_id_relative_path",
        "v2_node",
        ["version_id", "relative_path"],
        unique=True,
    )

    op.add_column("derived_contents", sa.Column("node_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_derived_contents_node_id"),
        "derived_contents",
        ["node_id"],
        unique=False,
    )
    op.create_foreign_key(None, "derived_contents", "v2_node", ["node_id"], ["id"])
    op.add_column(
        "derived_contents",
        sa.Column(
            "content_type_slug", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_derived_contents_content_type_slug"),
        "derived_contents",
        ["content_type_slug"],
        unique=False,
    )
    op.create_table(
        "v2_primary_asset_tag",
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column("primary_asset_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"]),
        sa.ForeignKeyConstraint(["primary_asset_id"], ["v2_primary_asset.id"]),
        sa.PrimaryKeyConstraint("tag_id", "primary_asset_id"),
    )

    op.execute("""
            CREATE VIEW v2_full_node AS
            SELECT
                pa.id AS primary_asset_id,
                pa.display_name AS primary_asset_display_name,
                pa.organization_id AS primary_asset_organization_id,
                pa.created_at AS primary_asset_created_at,
                pa.updated_at AS primary_asset_updated_at,
                pa.primary_asset_type AS primary_asset_primary_asset_type,
                v.id AS version_id,
                v.display_name AS version_display_name,
                v.created_at AS version_created_at,
                v.updated_at AS version_updated_at,
                n.id AS node_id,
                n.relative_path AS node_relative_path,
                n.created_at AS node_created_at,
                n.updated_at AS node_updated_at
            FROM
                v2_primary_asset pa
            LEFT JOIN
                v2_version v ON pa.id = v.primary_asset_id
            LEFT JOIN
                v2_node n ON v.id = n.version_id
               """)
    # MIGRATE CODEBASES

    op.execute(
        """
        -- CODEBASE -> PRIMARY ASSET
        --
        -- PRIMARY_ASSET.ID = EARLIEST CODEBASE ID
        --
        INSERT INTO v2_primary_asset (id, display_name, primary_asset_type, organization_id, created_at, updated_at)
        SELECT DISTINCT ON (c.codebase_name, w.organization_id) c.id, c.codebase_name, 'CODEBASE', w.organization_id, c.created_at, c.updated_at
        FROM codebases c
        JOIN workspaces w on w.id = c.workspace_id
        ORDER BY c.codebase_name, w.organization_id, c.created_at;
        """
    )

    op.execute(
        """
        -- CODEBASE -> VERSION
        --
        -- VERSION.ID [Grouped by CODEBASE NAME] = CODEBASE ID
        --
        INSERT INTO v2_version (id, primary_asset_id, display_name, created_at, updated_at)
        SELECT c.id, pa.id,
            '0.0.' || ROW_NUMBER() OVER (PARTITION BY w.organization_id, c.codebase_name ORDER BY c.created_at ASC) - 1,
            c.created_at, c.updated_at
        FROM codebases c
        JOIN workspaces w ON w.id = c.workspace_id
        JOIN v2_primary_asset pa ON pa.organization_id = w.organization_id
        WHERE pa.display_name = c.codebase_name;
        """
    )

    # NOTE: The root node is the lowest level directory, which exists with the same relative path as the codebase currently.
    # op.execute(
    #     """
    #     -- SOURCE CONTENT [Codebase] -> ROOT NODE
    #     --
    #     -- NODE.ID = SOURCE CONTENT [Files and Directories].ID
    #     --
    #     INSERT INTO v2_node (id, version_id, relative_path, created_at, updated_at)
    #     SELECT DISTINCT ON (dc.relative_path, v.id) dc.id, v.id, '', dc.created_at, dc.updated_at
    #     FROM derived_contents dc
    #     JOIN derived_content_types dc_type ON dc.content_type_id = dc_type.id
    #     JOIN v2_version v ON v.id = dc.codebase_id
    #     WHERE dc_type.type_name in ('codebase')
    #     """
    # )
    #

    print("Executing: SOURCE CONTENT [Directories] -> NODE")
    op.execute(
        """
        -- SOURCE CONTENT [Directories] -> NODE
        --
        -- NODE.ID = CONTENT.ID
        --
        INSERT INTO v2_node (id, version_id, relative_path, created_at, updated_at)
        SELECT DISTINCT ON (dc.relative_path, v.id) dc.id, v.id,
            CASE
                WHEN RIGHT(dc.relative_path, 1) = '/' THEN dc.relative_path
                ELSE dc.relative_path || '/'
            END AS relative_path,
            dc.created_at, dc.updated_at
        FROM derived_contents dc
        JOIN derived_content_types dc_type ON dc.content_type_id = dc_type.id
        JOIN v2_version v ON v.id = dc.codebase_id
        WHERE dc_type.type_name = 'codebase-directory'
        """
    )

    print("Executing: SOURCE CONTENT [Files] -> NODE")
    op.execute(
        """
        -- SOURCE CONTENT [Files] -> NODE
        --
        -- NODE.ID = CONTENT.ID
        --
        INSERT INTO v2_node (id, version_id, relative_path, created_at, updated_at)
        SELECT DISTINCT ON (dc.relative_path, v.id) dc.id, v.id, dc.relative_path, dc.created_at, dc.updated_at
        FROM derived_contents dc
        JOIN derived_content_types dc_type ON dc.content_type_id = dc_type.id
        JOIN v2_version v ON v.id = dc.codebase_id
        WHERE dc_type.type_name = 'codebase-file'
        """
    )

    # MIGRATE PDFs

    print("Executing: PDF -> PRIMARY ASSET")
    op.execute(
        """
        -- PDF -> PRIMARY ASSET
        --
        -- PRIMARY_ASSET.ID = EARLIEST SOURCE CONTENT (PDF) ID
        --
        INSERT INTO v2_primary_asset (id, display_name, primary_asset_type, organization_id, created_at, updated_at)
        SELECT DISTINCT ON (dc.relative_path, w.organization_id) dc.id, dc.content_name, 'FILE', w.organization_id, dc.created_at, dc.updated_at
        FROM derived_contents dc
        JOIN derived_content_types dct on dc.content_type_id = dct.id
        JOIN workspaces w on w.id = dc.workspace_id
        WHERE dct.type_name = 'supplemental-document'
        AND dc.source_content_id is NULL
        ORDER BY dc.relative_path, w.organization_id, dc.created_at;
        """
    )

    print("Executing: PDF -> VERSION")
    op.execute(
        """
        -- PDF -> VERSION
        --
        -- VERSION.ID = SOURCE CONTENT (PDF) ID
        --
        INSERT INTO v2_version (id, primary_asset_id, display_name, created_at, updated_at)
        SELECT dc.id, pa.id,
            '0.0.' || ROW_NUMBER() OVER (PARTITION BY w.organization_id, dc.content_name ORDER BY dc.created_at ASC) - 1,
            dc.created_at, dc.updated_at
        FROM derived_contents dc
        JOIN workspaces w ON w.id = dc.workspace_id
        JOIN v2_primary_asset pa ON pa.organization_id = w.organization_id
        JOIN derived_content_types dct on dct.id = dc.content_type_id
        WHERE dc.source_content_id IS NULL
        AND dct.type_name = 'supplemental-document'
        AND pa.display_name = dc.content_name;

        """
    )

    print("Executing: SOURCE CONTENT [PDF] -> NODE")
    op.execute(
        """
        -- SOURCE CONTENT [PDF] -> NODE
        --
        -- NODE.ID = SOURCE CONTENT [PDF].ID
        --
        INSERT INTO v2_node (id, version_id, relative_path, created_at, updated_at)
        SELECT dc.id, v.id, dc.relative_path, dc.created_at, dc.updated_at
        FROM derived_contents dc
        JOIN derived_content_types dc_type ON dc.content_type_id = dc_type.id
        JOIN v2_version v ON v.id = dc.id
        WHERE dc_type.type_name = 'supplemental-document';
        """
    )

    # MIGRATE PAGES

    print("Executing: PAGES -> PRIMARY ASSET")
    op.execute(
        """
        -- PAGES -> PRIMARY ASSET
        --
        -- PRIMARY_ASSET.ID = APPLICATION NOTE ID
        --
        INSERT INTO v2_primary_asset (id, display_name, primary_asset_type, organization_id, created_at, updated_at)
        SELECT dc.id,
            CASE
                WHEN ROW_NUMBER() OVER (PARTITION BY w.organization_id, dc.content_name ORDER BY dc.created_at) > 1
                THEN dc.content_name || '-' || (ROW_NUMBER() OVER (PARTITION BY w.organization_id, dc.content_name ORDER BY dc.created_at) - 1)::text
                ELSE dc.content_name
            END AS display_name,
            'PAGE',
            w.organization_id,
            dc.created_at,
            dc.updated_at
        FROM derived_contents dc
        JOIN derived_content_types dct on dc.content_type_id = dct.id
        JOIN workspaces w on w.id = dc.workspace_id
        WHERE dct.type_name = 'application_note'
        AND dc.content_name is not NULL;
        """
    )

    print("Executing: PAGES -> VERSION")
    op.execute(
        """
        -- PAGES -> VERSION
        --
        -- VERSION.ID = CONTENT (PAGE) ID
        --
        INSERT INTO v2_version (id, primary_asset_id, display_name, created_at, updated_at)
        SELECT dc.id, pa.id,
            '0.0.0',
            dc.created_at, dc.updated_at
        FROM derived_contents dc
        JOIN workspaces w ON w.id = dc.workspace_id
        JOIN v2_primary_asset pa ON pa.organization_id = w.organization_id
        JOIN derived_content_types dct on dct.id = dc.content_type_id
        WHERE dct.type_name = 'application_note'
        AND dc.id = pa.id;
        """
    )

    print("Executing: SOURCE CONTENT [PAGES] -> NODE")
    op.execute(
        """
        -- SOURCE CONTENT [PAGES] -> NODE
        --
        -- NODE.ID = SOURCE CONTENT [PAGES].ID
        --
        INSERT INTO v2_node (id, version_id, relative_path, created_at, updated_at)
        SELECT DISTINCT dc.id, v.id, dc.relative_path, dc.created_at, dc.updated_at
        FROM derived_contents dc
        JOIN derived_content_types dc_type ON dc.content_type_id = dc_type.id
        JOIN v2_version v ON v.id = dc.id
        where dc_type.type_name = 'application_note'
        """
    )

    print("Executing: Update derived_contents with content_type_slug")
    op.execute(
        """
        UPDATE derived_contents
        SET content_type_slug = dc_type.type_name
        FROM derived_content_types dc_type
        WHERE derived_contents.content_type_id = dc_type.id;
        """
    )

    print("Executing: Update derived_contents with node_id for non-standard types")
    op.execute(
        """
        UPDATE derived_contents
        SET node_id = v2_node.id
        FROM v2_node
        WHERE content_type_slug NOT IN ('codebase', 'codebase-directory', 'codebase-file', 'application_note', 'supplemental-document')
        AND v2_node.id = source_content_id
        AND derived_contents.node_id is NULL;
        """
    )

    print("Executing: Update derived_contents with node_id for application_note")
    op.execute(
        """
        UPDATE derived_contents
        SET node_id = v2_node.id
        FROM v2_node
        WHERE v2_node.id = derived_contents.id
        AND derived_contents.content_type_slug = 'application_note'
        AND derived_contents.node_id is NULL;
        """
    )

    print("Executing: Update derived_contents with node_id for codebase")
    op.execute(
        """
        UPDATE derived_contents
        SET node_id = n.id
        FROM v2_node n
        JOIN v2_version v on n.version_id = v.id
        JOIN derived_contents sc on sc.content_type_slug = 'codebase'
        WHERE sc.codebase_id = derived_contents.codebase_id
        AND v.id = derived_contents.codebase_id
        AND sc.id = derived_contents.source_content_id
        AND (n.relative_path = derived_contents.relative_path OR n.relative_path = derived_contents.relative_path || '/')
        AND derived_contents.node_id is NULL;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    print("Executing: DROP TABLE v2_primary_asset_tags")
    op.drop_table("v2_primary_asset_tags")
    # ### commands auto generated by Alembic - please adjust! ###
    print("Executing: DROP VIEW IF EXISTS v2_full_node")
    op.execute("DROP VIEW IF EXISTS v2_full_node")

    print("Executing: DROP INDEX ix_derived_contents_node_id on derived_contents")
    op.drop_index(op.f("ix_derived_contents_node_id"), table_name="derived_contents")

    print(
        "Executing: DROP INDEX ix_derived_contents_content_type_slug on derived_contents"
    )
    op.drop_index(
        op.f("ix_derived_contents_content_type_slug"), table_name="derived_contents"
    )

    print("Executing: DROP COLUMN content_type_slug from derived_contents")
    op.drop_column("derived_contents", "content_type_slug")

    print("Executing: DROP COLUMN node_id from derived_contents")
    op.drop_column("derived_contents", "node_id")

    print("Executing: DROP INDEX ix_version_id_relative_path on v2_node")
    op.drop_index("ix_version_id_relative_path", table_name="v2_node")

    print("Executing: DROP TABLE v2_node")
    op.drop_table("v2_node")

    print(
        "Executing: DROP INDEX ix_v2_version_primary_asset_id_display_name on v2_version"
    )
    op.drop_index(
        "ix_v2_version_primary_asset_id_display_name", table_name="v2_version"
    )

    print("Executing: DROP TABLE v2_version")
    op.drop_table("v2_version")

    print(
        "Executing: DROP INDEX ix_v2_primary_asset_organization_id_display_name on v2_primary_asset"
    )
    op.drop_index(
        "ix_v2_primary_asset_organization_id_display_name",
        table_name="v2_primary_asset",
    )

    print("Executing: DROP TABLE v2_primary_asset")
    op.drop_table("v2_primary_asset")

    # ### end Alembic commands ###
