"""adding code_symbol contentType

Revision ID: 0d7d67c8730d
Revises: faa8d977ae43
Create Date: 2024-03-13 13:50:54.609993

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d7d67c8730d"
down_revision: Union[str, None] = "faa8d977ae43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE contenttype ADD VALUE 'CODE_SYMBOL'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
