"""index version recency

Revision ID: b1466ca58da1
Revises: bf955986b171
Create Date: 2025-03-10 14:52:46.669937

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b1466ca58da1"
down_revision = "bf955986b171"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "v2_version",
        sa.Column(
            "is_head", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.create_index(
        "ix_version_primary_asset_id_updated_at_desc",
        "v2_version",
        ["primary_asset_id", sa.literal_column("updated_at DESC")],
        unique=False,
    )
    op.execute(
        """
        UPDATE v2_version
        SET is_head = TRUE
        WHERE id IN (
            SELECT id
            FROM (
                SELECT id,
                       ROW_NUMBER() OVER (
                           PARTITION BY primary_asset_id
                           ORDER BY updated_at DESC
                       ) AS rn
                FROM v2_version
            ) AS sub
            WHERE sub.rn = 1
        )
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_version_primary_asset_id_updated_at_desc", table_name="v2_version"
    )
    op.drop_column("v2_version", "is_head")
    # ### end Alembic commands ###
