"""cleanup models

Revision ID: 27b2b49b3e7e
Revises: e07bf18dd991
Create Date: 2025-01-16 15:17:45.011254

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27b2b49b3e7e'
down_revision = 'e07bf18dd991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_codebases_workspace_id', table_name='codebases')
    op.drop_table('codebases')
    op.drop_table('workspaces')
    op.drop_table('inspection_versions')
    op.drop_table('tags_contents')
    op.drop_table('derived_content_types')
    op.drop_index('ix_chunkandembedding___ts_vector__', table_name='chunkandembedding', postgresql_using='gin')
    op.drop_index('ix_chunkandembedding_text_embedding_3_small_vector_l2_ops', table_name='chunkandembedding', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_constraint('chunkandembedding_content_id_fkey', 'chunkandembedding', type_='foreignkey')
    op.create_foreign_key(None, 'chunkandembedding', 'derived_contents', ['content_id'], ['id'])
    op.drop_column('chunkandembedding', '__ts_vector__')
    op.drop_index('derived_contents_metadata_idx', table_name='derived_contents', postgresql_using='gin')
    op.drop_index('ix_derived_contents_codebase_id', table_name='derived_contents')
    op.drop_index('ix_derived_contents_content_name', table_name='derived_contents')
    op.drop_index('ix_derived_contents_content_type_id', table_name='derived_contents')
    op.drop_index('ix_derived_contents_source_content_id', table_name='derived_contents')
    op.drop_index('ix_derived_contents_workspace_id', table_name='derived_contents')
    op.drop_column('derived_contents', 'workspace_id')
    op.drop_column('derived_contents', 'codebase_id')
    op.drop_constraint('document_sources_document_id_fkey', 'document_sources', type_='foreignkey')
    op.drop_constraint('document_sources_source_id_fkey', 'document_sources', type_='foreignkey')
    op.drop_column('document_sources', 'source_id')
    op.drop_column('document_sources', 'include')
    op.drop_column('document_sources', 'document_id')
    op.drop_column('runtimelogagentinstance', 'workspace_id')
    op.drop_column('runtimelogagentinstance', 'codebase_id')
    op.drop_index('ix_tag_type', table_name='tags')
    op.alter_column('v2_node', 'kind',
               existing_type=postgresql.ENUM('CODEBASE_FILE', 'CODEBASE_DIRECTORY', 'OTHER', name='enum_node_kind'),
               type_=sa.Enum('CODEBASE_FILE', 'CODEBASE_DIRECTORY', 'OTHER', name='nodekind'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('v2_node', 'kind',
               existing_type=sa.Enum('CODEBASE_FILE', 'CODEBASE_DIRECTORY', 'OTHER', name='nodekind'),
               type_=postgresql.ENUM('CODEBASE_FILE', 'CODEBASE_DIRECTORY', 'OTHER', name='enum_node_kind'),
               existing_nullable=False)
    op.create_index('ix_tag_type', 'tags', ['type'], unique=False)
    op.add_column('runtimelogagentinstance', sa.Column('codebase_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('runtimelogagentinstance', sa.Column('workspace_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('document_sources', sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('document_sources', sa.Column('include', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('document_sources', sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('document_sources_source_id_fkey', 'document_sources', 'derived_contents', ['source_id'], ['id'])
    op.create_foreign_key('document_sources_document_id_fkey', 'document_sources', 'derived_contents', ['document_id'], ['id'])
    op.add_column('derived_contents', sa.Column('codebase_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('derived_contents', sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index('ix_derived_contents_workspace_id', 'derived_contents', ['workspace_id'], unique=False)
    op.create_index('ix_derived_contents_source_content_id', 'derived_contents', ['source_content_id'], unique=False)
    op.create_index('ix_derived_contents_content_type_id', 'derived_contents', ['content_type_id'], unique=False)
    op.create_index('ix_derived_contents_content_name', 'derived_contents', ['content_name'], unique=False)
    op.create_index('ix_derived_contents_codebase_id', 'derived_contents', ['codebase_id'], unique=False)
    op.create_index('derived_contents_metadata_idx', 'derived_contents', ['metadata'], unique=False, postgresql_using='gin')
    op.add_column('chunkandembedding', sa.Column('__ts_vector__', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, (text)::text)", persisted=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chunkandembedding', type_='foreignkey')
    op.create_foreign_key('chunkandembedding_content_id_fkey', 'chunkandembedding', 'derived_contents', ['content_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_chunkandembedding_text_embedding_3_small_vector_l2_ops', 'chunkandembedding', ['text_embedding_3_small'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('ix_chunkandembedding___ts_vector__', 'chunkandembedding', ['__ts_vector__'], unique=False, postgresql_using='gin')
    op.create_table('derived_content_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('type_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='derived_content_types_pkey'),
    sa.UniqueConstraint('type_name', name='derived_content_types_type_name_key')
    )
    op.create_table('tags_contents',
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('include', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['derived_contents.id'], name='tags_contents_content_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='tags_contents_tag_id_fkey'),
    sa.PrimaryKeyConstraint('tag_id', 'content_id', name='tags_contents_pkey')
    )
    op.create_table('inspection_versions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('previous_version_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='inspection_versions_pkey')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='workspaces_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('codebases',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('codebase_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('processing', 'processing-complete', 'processing-error', 'codebase-rejected', name='enum_codebase_status'), autoincrement=False, nullable=False),
    sa.Column('storage_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resource_root', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name='codebases_workspace_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='codebases_pkey'),
    sa.UniqueConstraint('workspace_id', 'codebase_name', name='uq_workspace_id_codebase_name')
    )
    op.create_index('ix_codebases_workspace_id', 'codebases', ['workspace_id'], unique=False)
    # ### end Alembic commands ###
