"""drop version id relative path unique constraint

Revision ID: d452ba9937ab
Revises: 4e793ad782c2
Create Date: 2025-10-30 12:14:08.909275

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "d452ba9937ab"
down_revision = "4e793ad782c2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_version_id_relative_path", table_name="node")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_version_id_relative_path",
        "node",
        ["version_id", "relative_path"],
        unique=True,
    )
    # ### end Alembic commands ###
