"""index version status

Revision ID: 4ec484ef0f5b
Revises: 3b2cb97a373b
Create Date: 2025-02-11 14:49:02.407123

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "4ec484ef0f5b"
down_revision = "3b2cb97a373b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_v2_version_status"), "v2_version", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_v2_version_status"), table_name="v2_version")
    # ### end Alembic commands ###
