"""Create UserCache table

Revision ID: 57850d6e8126
Revises: 2c5d9d6cbdb5
Create Date: 2025-03-04 15:21:34.186567

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "57850d6e8126"
down_revision = "2c5d9d6cbdb5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_cache",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "v2_version",
        sa.Column("creator_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_foreign_key(
        None, "v2_version", "user_cache", ["creator_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "v2_version", type_="foreignkey")
    op.drop_column("v2_version", "creator_id")
    op.drop_table("user_cache")
    # ### end Alembic commands ###
