"""org and kind indexes

Revision ID: 17adb3b30d26
Revises: 3b2cb97a373b
Create Date: 2025-02-10 15:58:01.491888

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "17adb3b30d26"
down_revision = "3b2cb97a373b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_v2_primary_asset_kind"), "v2_primary_asset", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_v2_primary_asset_organization_id"),
        "v2_primary_asset",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_v2_primary_asset_organization_id"), table_name="v2_primary_asset"
    )
    op.drop_index(op.f("ix_v2_primary_asset_kind"), table_name="v2_primary_asset")
    # ### end Alembic commands ###
