"""indices

Revision ID: 306ce48d3c06
Revises: 3b2cb97a373b
Create Date: 2025-02-10 16:32:25.557790

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "306ce48d3c06"
down_revision = "3b2cb97a373b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_v2_node_version_id"), "v2_node", ["version_id"], unique=False
    )
    op.drop_index(
        "ix_v2_primary_asset_organization_id_display_name",
        table_name="v2_primary_asset",
    )
    op.create_index(
        op.f("ix_v2_primary_asset_display_name"),
        "v2_primary_asset",
        ["display_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_primary_asset_kind"), "v2_primary_asset", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_v2_primary_asset_organization_id"),
        "v2_primary_asset",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_v2_primary_asset_organization_id_display_name_kind",
        "v2_primary_asset",
        ["organization_id", "display_name", "kind"],
        unique=True,
    )
    op.create_index(
        op.f("ix_v2_primary_asset_tag_primary_asset_id"),
        "v2_primary_asset_tag",
        ["primary_asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_primary_asset_tag_tag_id"),
        "v2_primary_asset_tag",
        ["tag_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_version_primary_asset_id"),
        "v2_version",
        ["primary_asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_v2_version_updated_at"), "v2_version", ["updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_v2_version_updated_at"), table_name="v2_version")
    op.drop_index(op.f("ix_v2_version_primary_asset_id"), table_name="v2_version")
    op.drop_index(
        op.f("ix_v2_primary_asset_tag_tag_id"), table_name="v2_primary_asset_tag"
    )
    op.drop_index(
        op.f("ix_v2_primary_asset_tag_primary_asset_id"),
        table_name="v2_primary_asset_tag",
    )
    op.drop_index(
        "ix_v2_primary_asset_organization_id_display_name_kind",
        table_name="v2_primary_asset",
    )
    op.drop_index(
        op.f("ix_v2_primary_asset_organization_id"), table_name="v2_primary_asset"
    )
    op.drop_index(op.f("ix_v2_primary_asset_kind"), table_name="v2_primary_asset")
    op.drop_index(
        op.f("ix_v2_primary_asset_display_name"), table_name="v2_primary_asset"
    )
    op.create_index(
        "ix_v2_primary_asset_organization_id_display_name",
        "v2_primary_asset",
        ["organization_id", "display_name"],
        unique=True,
    )
    op.drop_index(op.f("ix_v2_node_version_id"), table_name="v2_node")
    # ### end Alembic commands ###
