"""adds VersionNode table and columns to Node

Revision ID: 4e793ad782c2
Revises: cf24527010fc
Create Date: 2025-10-30 10:12:14.715772

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "4e793ad782c2"
down_revision = "cf24527010fc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "version_node",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("relative_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("primary_asset_id", sa.Uuid(), nullable=False),
        sa.Column("node_content_id", sa.Uuid(), nullable=False),
        sa.Column(
            "depth",
            sa.Integer(),
            sa.Computed(
                "length(trim(trailing '/' from relative_path)) - length(replace(trim(trailing '/' from relative_path), '/', ''))",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["node_content_id"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["primary_asset_id"],
            ["primary_asset.id"],
        ),
        sa.ForeignKeyConstraint(["version_id"], ["version.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("version_id", "relative_path"),
    )
    op.create_index(
        op.f("ix_version_node_depth"), "version_node", ["depth"], unique=False
    )
    op.create_index(
        op.f("ix_version_node_relative_path"),
        "version_node",
        ["relative_path"],
        unique=False,
    )
    op.create_index(
        op.f("ix_version_node_version_id"), "version_node", ["version_id"], unique=False
    )
    op.add_column(
        "node",
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("node", sa.Column("primary_asset_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_node_primary_asset_id"), "node", ["primary_asset_id"], unique=False
    )
    op.create_foreign_key(
        None, "node", "primary_asset", ["primary_asset_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_node_primary_asset_id"), table_name="node")
    op.drop_column("node", "primary_asset_id")
    op.drop_column("node", "content_hash")
    op.drop_index(op.f("ix_version_node_version_id"), table_name="version_node")
    op.drop_index(op.f("ix_version_node_relative_path"), table_name="version_node")
    op.drop_index(op.f("ix_version_node_depth"), table_name="version_node")
    op.drop_table("version_node")
    # ### end Alembic commands ###
