"""index version recency

Revision ID: 141fd4e3a2d4
Revises: bf955986b171
Create Date: 2025-03-10 12:58:14.454801

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "141fd4e3a2d4"
down_revision = "bf955986b171"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "v2_primary_asset",
        sa.Column("most_recent_version_id", sa.Uuid(), nullable=True),
    )
    op.create_index(
        op.f("ix_v2_primary_asset_most_recent_version_id"),
        "v2_primary_asset",
        ["most_recent_version_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "v2_primary_asset", "v2_version", ["most_recent_version_id"], ["id"]
    )
    op.create_index(
        "ix_version_primary_asset_id_updated_at_desc",
        "v2_version",
        ["primary_asset_id", sa.literal_column("updated_at DESC")],
        unique=False,
    )
    # Populate the most_recent_version_id with the version_id having the most recent updated_at for each primary_asset
    op.execute(
        """
        UPDATE v2_primary_asset
        SET most_recent_version_id = subquery.id
        FROM (
            SELECT v2_version.id, v2_version.primary_asset_id
            FROM v2_version
            JOIN (
                SELECT primary_asset_id, MAX(updated_at) AS max_updated_at
                FROM v2_version
                GROUP BY primary_asset_id
            ) AS max_dates
            ON v2_version.primary_asset_id = max_dates.primary_asset_id
            AND v2_version.updated_at = max_dates.max_updated_at
        ) AS subquery
        WHERE v2_primary_asset.id = subquery.primary_asset_id
    """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_version_primary_asset_id_updated_at_desc", table_name="v2_version"
    )
    op.drop_constraint(None, "v2_primary_asset", type_="foreignkey")
    op.drop_index(
        op.f("ix_v2_primary_asset_most_recent_version_id"),
        table_name="v2_primary_asset",
    )
    op.drop_column("v2_primary_asset", "most_recent_version_id")
    # ### end Alembic commands ###
