name: 'Modal Deployment'
description: 'Deploy a modal package'
inputs:
  working-directory:
    description: 'The directory of the modal package to be deployed'
    required: true
  package-name:
    description: 'The name of the modal package to be deployed'
    required: true
runs:
  using: 'composite'
  steps:
   - name: Install dependencies
     shell: bash
     working-directory: ${{ inputs.working-directory }}
     run: poetry install --no-root
   - name: Run Tests
     shell: bash
     working-directory: ${{ inputs.working-directory }}
     run: poetry run pytest
  #  - name: Deploy ${{ inputs.package-name }}
  #    working-directory: ${{ inputs.working-directory }}
  #    env:
  #      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
  #      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
  #      MODAL_ENV: ${{ vars.MODAL_ENV }}
  #    run: poetry run modal deploy --env=$MODAL_ENV --tag=${GITHUB_SHA::8} src/main.py