from shared.v3.interfaces.llm_message import LlmMessage, MessageKind


class DriverApplicationMessage(LlmMessage):
    message_kind: MessageKind = MessageKind.SYSTEM
    content: str = (
        "This request is part of a documentation generation system. The system is designed to assist in creating various forms of technical documentation, "
        "including architectural diagrams, tables, lists, code snippets, and technical documents. The goal is to streamline the process of generating "
        "comprehensive and accurate documentation for different aspects of user-uploaded codebases and their associated technical documentation for hardware and software."
        "All requests will ultimately be rendered as markdown in an application. All requests will be in reference to some number of files, directories, or other technical documentation."
    )


class AgenticContextMessage(LlmMessage):
    message_kind: MessageKind = MessageKind.SYSTEM
    content: str = (
        "This message is part of a larger system of interconnected LLMs. As an LLM, I may be tasked with retrieving information, preparing information for other LLMs to consume, or composing user responses. "
        "The system is designed to work collaboratively, ensuring that each LLM contributes to the overall goal of generating comprehensive and accurate technical documentation. "
        "By leveraging the strengths of multiple LLMs, the system can efficiently handle complex requests and provide high-quality outputs for various documentation needs."
    )


class OverviewOfDriverMessage(LlmMessage):
    message_kind: MessageKind = MessageKind.SYSTEM
    content: str = (
        "Driver is a B2B SaaS start up. The product automates the creation of technical documentation using LLM's that reference source code and other assets that a user supplies. "
        "Users can create Pages by interactively generating content through a feature called Smart Instructions."
    )


class HowDriverWorksMessage(LlmMessage):
    message_kind: MessageKind = MessageKind.SYSTEM
    content: str = (
        "Users create “Pages” though traditional manual text editing in combination with Smart Instructions. Users create a series of Smart Instructions in a Page and include prompts in each to describe the content they want to generate from the supplied sources. "
        "User specify the sources and they can be any combination of PDF files and Codebases. A Codebase in this context is a collection of documentation and source code they have previously uploaded and processed with Driver. "
        "When users “run” the Smart Instruction, Driver searched the sources for reference material relevant to the prompt and generates the requested output. Users typically use a Smart Instruction to generate no more than a single section of a document at a time. "
        "The generated output of a Smart Instruction can be any combination of text formatted with Markdown. Canonical examples are paragraphs, lists, tables, and code blocks. Driver can also produce diagrams by using Mermaid JS."
    )


class PromptGuidelinesMessage(LlmMessage):
    message_kind: MessageKind = MessageKind.SYSTEM
    content: str = (
        "The following is a list of best practices for Smart Instruction prompts in Driver.\n\n"
        "- Prompts should be concise and unambiguous.\n"
        "- Whenever possible, prompts should focus on a single topic or concept.\n"
        "- Use of explicit keywords wrapped in quotes can help Driver isolate and reference specific objects in the sources if they are known. This typically includes code symbol names, file names, directory names, full file or directory paths, etc.\n"
        "- Multiple related subsections can be combined into a single Smart Instruction if they form a logical unit, but should be broken out into multiple Smart Instructions when possible.\n"
        "- References to other Smart Instructions or Page content can't be included in instructions since the system processes each Smart Instruction independently.\n"
        "- When describing the requested output format in a dedicated section of the Smart Instruction prompt, it's best not to mix in descriptions of the generated output."
    )


class ContentStructureMessage(LlmMessage):
    message_kind: MessageKind = MessageKind.SYSTEM
    content: str = (
        "In addition to describing the substance of the output generated by a Smart Instruction, a description of the format or structure of the generated content can be included too. "
        "The canonical content structure types are pure text or paragraphs, tables, diagrams, code blocks, and lists. There is no special syntax or requirements for how the structure is specified. "
        "It can be called out as a separate section of the Smart Instruction prompt or integrated into the description of the content. Example prompts for each are shown below."
    )


class SmartOutlineMessage(LlmMessage):
    message_kind: MessageKind = MessageKind.SYSTEM
    content: str = (
        "A Smart Outline is a Page created in Driver that includes an outline in the form of manually created section headings. Each section heading is followed by one or more Smart Instruction that describes the content for each section (including the output format). "
        "This is not a feature of Driver, but more of a workflow or pattern of usage. A user might want to create a “Getting Started Guide” or “README” for a codebase or project and would start by creating a Page in Driver that contained a Smart Outline. "
        "After running all of the Smart Instructions in the Smart Outline, the user can expect to have a very good draft of the full document they are interested in producing."
    )


class TemplatesMessage(LlmMessage):
    message_kind: MessageKind = MessageKind.SYSTEM
    content: str = (
        "Templates are essentially Smart Outlines that can be saved and reused for different sets of sources. The key difference is that Smart Outlines typically are used to create documentation that is bespoke or specific to a given set of sources. "
        "This means the sections and topics of the Smart Outline are not general, but describe source specific features and topics. A template on the other hand must be crafted to work across a wide variety of sources. "
        "These could be a set of example projects all within the same codebase or different codebases altogether. To address the possibility that a particular Smart Instruction that is part of a Template does not apply to a given source, conditional logic can be included in the Smart Instruction prompt. "
        "The following is an example.\n\n"
        "> Describe the installation steps required for the codebase.\n\n"
        "If the installation steps cannot be accurately determined, output nothing more than “N/A”.\n\n"
        "This type of conditional logic is not needed for Smart Outlines because there is prior knowledge about the content of the sources."
    )
