[tool.poetry]
name = "pdf-preprocessing"
version = "0.1.0"
description = ""
authors = ["Eric Miller <146128069+eric-driverai@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
pymupdf = "^1.24.7"
openai = "^1.35.12"
database = {path = "../../driver_db", develop = true}
shared = {path = "../../packages/shared", develop = true}
boto3 = "^1.34.141"
pydantic = "^2.8.2"
pydantic-settings = "^2.3.4"
tiktoken = "^0.7.0"
greenlet = "^3.0.3"
modal = "^0.63.55"
asyncio = "^3.4.3"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
