[tool.poetry]
name = "inspector"
version = "0.1.0"
description = ""
authors = ["Andrew Mark <andrewemark@gmail.com>"]
readme = "README.md"
packages = [{include = "src.inspection"}, {include = "src.utils"}]

# Note: this file is just used to create the venv for the local ide. Modal installs the dependencies for the containers
[tool.poetry.dependencies]
python = "^3.12"
modal = "^0.62.170"
openai = "^1.30.1"
tiktoken = "^0.7.0"
tqdm = "^4.66.4"
boto3 = "^1.34.114"
database = {path = "../../driver_db", develop = true}


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
moto = "^5.0.9"
pytest-asyncio = "^0.23.7"
python-dotenv = "^1.0.1"
ruff = "^0.5.5"
ipython = "^8.26.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
