from pydantic import BaseModel
from shared import prompts
from shared.agent.agent_factory import create_agent
from shared.interfaces.agents.pipeline_configuration import (
    PipelineStepConfiguration,
    PipelineStepResponse,
)
from shared.usage.llm_session import LLMUsageSession


class PromptAugmentationLLMResponse(BaseModel):
    """
    A response model for prompt augmentation.

    Attributes:
        new_prompt (str): The augmented prompt generated by the agent.
        rationale (str): The explanation or rationale behind the changes made to the original prompt.
    """

    new_prompt: str
    rationale: str


def run_agent_prompt_augmentation(
    input: PipelineStepConfiguration, llm_session: LLMUsageSession
) -> PipelineStepResponse:
    prompt_text = input.prompt.prompt

    # Don't transform the prompt if longer than 100 words. It means there's enough detail.
    if len(prompt_text.split()) > 100:
        return PipelineStepResponse(
            agent_id=None, search_results=[], agent_result=input.prompt.prompt
        )

    agent = create_agent(
        scope=input.scope,
        model=input.model,
        max_iterations=input.iterations,
        tools=input.tools,
        response_type=PromptAugmentationLLMResponse,
        llm_session=llm_session,
    )

    agent.add_message(prompts.voice.software_engineer.MESSAGE)
    agent.add_message(prompts.task.prompt_augmentation.MESSAGE)
    for system_prompt in input.create_system_prompts():
        agent.add_message(system_prompt)

    response = agent.invoke(str(input.prompt))

    return PipelineStepResponse(
        agent_id=agent.agent_id,
        search_results=agent.search_results,
        agent_result=response.new_prompt,
    )
