from pydantic import BaseModel
from shared import prompts
from shared.agent.agent_factory import create_agent
from shared.agent.tools.search_tool import SearchTool
from shared.interfaces.agents.pipeline_configuration import (
    PipelineStepConfiguration,
    PipelineStepResponse,
    PromptWithContext,
)


class PromptAugmentationLLMResponse(BaseModel):
    """
    A response model for prompt augmentation.

    Attributes:
        new_prompt (str): The augmented prompt generated by the agent.
        additional_context (dict): Additional context that might be necessary to pass into an LLM
                                   in order to get the correct results. This can any other relevant details that can
                                   help the LLM generate a more accurate and relevant prompt, and explains how the prompt's response
                                   might be used.
        rationale (str): The explanation or rationale behind the changes made to the original prompt.
    """

    new_prompt: str
    additional_context: str
    rationale: str


def run_agent_prompt_augmentation(
    input: PipelineStepConfiguration,
) -> PipelineStepResponse:
    agent = create_agent(
        model=input.model,
        organization_id=input.scope.organization_id,
        max_iterations=input.iterations,
        tools=[SearchTool],
        paths=input.scope.paths,
        response_type=PromptAugmentationLLMResponse,
    )
    agent.add_message(prompts.interface.batch_tools.MESSAGE)
    agent.add_message(prompts.interface.technical_context_interface.MESSAGE)
    agent.add_message(prompts.voice.software_engineer.MESSAGE)
    agent.add_message(prompts.task.prompt_augmentation.MESSAGE)
    response = agent.invoke(str(input.prompt))

    return PipelineStepResponse(
        agent_id=agent.agent_id,
        search_results=agent.search_results,
        agent_result=str(
            PromptWithContext(prompt=response.new_prompt, context=input.prompt.context)
        ),
    )
