from pydantic import BaseModel
from shared import prompts
from shared.agent.agent_factory import create_agent
from shared.agent.tools import SearchTool
from shared.interfaces.agents.execute import (
    AgentConfiguration,
    AgentScope,
    UserPromptWithContext,
)


class PromptAugmentationResponse(BaseModel):
    """
    A response model for prompt augmentation.

    Attributes:
        new_prompt (str): The augmented prompt generated by the agent.
        additional_context (dict): Additional context that might be necessary to pass into an LLM
                                   in order to get the correct results. This can any other relevant details that can
                                   help the LLM generate a more accurate and relevant prompt, and explains how the prompt's response
                                   might be used.
        rationale (str): The explanation or rationale behind the changes made to the original prompt.
    """

    new_prompt: str
    additional_context: dict
    rationale: str


def run_agent_prompt_augmentation(
    prompt: str, agent_config: AgentConfiguration, scope: AgentScope
) -> str:
    agent = create_agent(
        model=agent_config.model,
        organization_id=scope.organization_id,
        max_iterations=3,
        tools=[SearchTool],
        paths=scope.paths,
        response_type=PromptAugmentationResponse,
    )
    agent.add_message(prompts.interface.batch_tools.MESSAGE)
    agent.add_message(prompts.interface.technical_context_interface.MESSAGE)
    agent.add_message(prompts.voice.software_engineer.MESSAGE)
    agent.add_message(prompts.task.prompt_augmentation.MESSAGE)
    response = agent.invoke(prompt)
    return UserPromptWithContext(
        prompt=response.new_prompt, context=response.additional_context
    ).create_user_prompt()
