name: Publish Coverage Report

on:
  workflow_run:
    workflows: [Test]
    types: [completed]

permissions:
  statuses: write
  contents: read
  actions: read

jobs:
  pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages'  # Ensure this is the branch configured for GitHub Pages

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Download Coverage Report
        uses: dawidd6/action-download-artifact@v3.1.2
        with:
          workflow: test.yml
          commit: ${{ github.event.workflow_run.head_sha }}
          name: coverage-html-${{ github.event.workflow_run.run_id }}

      - name: Move and Prepare for GitHub Pages
        run: |
          mkdir -p coverage/${{ github.event.workflow_run.head_sha }}
          mv coverage-html/* coverage/${{ github.event.workflow_run.head_sha }}

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add coverage/
          git commit -m "Deploying coverage report for ${{ github.event.workflow_run.head_sha }}"
          git push
