name: Backend Dev and Ops Deployment
on:
  push:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  # TODO:
  # unittest:
  #   runs-on: ubuntu-latest
  #   environment: development
  # integrationTest:
  development:
    # needs: unittest
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - run: npm ci
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - run: poetry install --no-root
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.AWS_CICD_ROLE }}
      - name: CDK Synth
        env:
          DEPLOYMENT_ENVIRONMENT: development
        run: npx cdk synth > template.yaml
      - name: Archive generated CloudFormation template
        uses: actions/upload-artifact@v4
        with:
          name: CloudFormation Template
          path: dev-template.yaml
      - name: CDK Deploy
        env:
          DEPLOYMENT_ENVIRONMENT: development
        run: npx cdk deploy --require-approval never
  ops:
    # needs: unittest
    runs-on: ubuntu-latest
    environment: ops
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - run: npm ci
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - run: poetry install --no-root
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.AWS_CICD_ROLE }}
      - name: CDK Synth
        env:
          DEPLOYMENT_ENVIRONMENT: ops
        run: npx cdk synth > template.yaml
      - name: Archive generated CloudFormation template
        uses: actions/upload-artifact@v4
        with:
          name: CloudFormation Template
          path: ops-template.yaml
      - name: CDK Deploy
        env:
          DEPLOYMENT_ENVIRONMENT: ops
        run: npx cdk deploy --require-approval never
