[llms.default]
model_id = "gpt-4o"
provider = "openai"
max_context_window = 128000
optimal_context_window = 64000
max_output_tokens = 16384

[llms.gpt_4o]
model_id = "gpt-4o"
provider = "openai"
max_context_window = 128000
optimal_context_window = 64000
max_output_tokens = 16384

[llms.gpt_4o_mini]
model_id = "gpt-4o-mini"
provider = "openai"
max_context_window = 128000
optimal_context_window = 64000
max_output_tokens = 16384

[llms.o1]
model_id = "o1"
provider = "openai"
max_context_window = 200000
optimal_context_window = 100000
max_output_tokens = 100000

[llms.o1_mini]
model_id = "o1-mini"
provider = "openai"
max_context_window = 128000
optimal_context_window = 64000
max_output_tokens = 65536


# [models.gpt_4o]
# model_id = "gpt-4o-2024-08-06"
# provider = "openai"
# context_window_size = 128000
# max_output_tokens = 16384

# [models.gpt_4o_mini]
# model_id = "gpt-4o-mini"
# provider = "openai"
# context_window_size = 128000
# max_output_tokens = 4096

# [models.gpt_3_5_turbo]
# model_id = "gpt-3.5-turbo"
# provider = "openai"
# context_window_size = 16000
# max_output_tokens = 4096

# [models.claude_3_sonnet]
# model_id = "claude-3-5-sonnet-20240620"
# provider = "anthropic"
# context_window_size = 200000
# max_output_tokens = 4096

# [models.claude_3_5_haiku]
# model_id = "claude-3-5-haiku"
# provider = "anthropic"
# context_window_size = 200000
# max_output_tokens = 4096

# [models.claude_3_5_opus]
# model_id = "claude-3-5-opus"
# provider = "anthropic"
# context_window_size = 200000
# max_output_tokens = 4096

# [models.gemini]
# model_id = "gemini-1"
# provider = "google"
# context_window_size = 10240
# max_output_tokens = 5120
